version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: vlingo_postgres
    volumes:
       - vlingo_symbio_jdbc_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: vlingo_test
      POSTGRES_PASSWORD: vlingo123
  mysql:
    image: mysql:latest
    container_name: vlingo_mysql
    volumes:
       - vlingo_symbio_jdbc_mysql
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: vlingo123
      MYSQL_USER: vlingo_test
      MYSQL_PASSWORD: vlingo123
      MYSQL_DATABASE: vlingo_test

volumes:
  vlingo_symbio_jdbc_postgres:
  vlingo_symbio_jdbc_mysql:
